"""init models

Revision ID: e7af620772b3
Revises: 
Create Date: 2025-09-21 12:06:24.935751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7af620772b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('garments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fit', sa.Enum('regular', 'classic', 'slim', 'athletic', 'relaxed', 'oversized', 'missy', 'cropped', name='fit_enum'), nullable=True),
    sa.Column('chest_circumference', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist_circumference', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_circumference', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shoulder_width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sleeve_length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_garments_id'), 'garments', ['id'], unique=True)
    op.create_table('mannequins',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender_enum'), nullable=False),
    sa.Column('total_height', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('chest_circumference', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('waist_circumference', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('shoulder_width', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_circumference', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('arm_length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('inseam', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('back_length', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('arm_length IS NULL OR arm_length > 0', name='check_arm_positive'),
    sa.CheckConstraint('back_length IS NULL OR back_length > 0', name='check_back_positive'),
    sa.CheckConstraint('chest_circumference > 0', name='check_chest_positive'),
    sa.CheckConstraint('hip_circumference IS NULL OR hip_circumference > 0', name='check_hip_positive'),
    sa.CheckConstraint('inseam IS NULL OR inseam > 0', name='check_inseam_positive'),
    sa.CheckConstraint('shoulder_width IS NULL OR shoulder_width > 0', name='check_shoulder_positive'),
    sa.CheckConstraint('total_height > 0', name='check_total_height_positive'),
    sa.CheckConstraint('waist_circumference > 0', name='check_waist_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mannequins_id'), 'mannequins', ['id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('mannequin_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['mannequin_id'], ['mannequins.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mannequin_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.create_table('generated_images',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mannequin_id', sa.String(length=36), nullable=True),
    sa.Column('garment_id', sa.String(length=36), nullable=True),
    sa.Column('view', sa.Enum('front', 'side', 'back', 'three_quarters', name='view_enum'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'ready', 'failed', name='status_enum'), nullable=False),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('generation_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['mannequin_id'], ['mannequins.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generated_images_garment_id'), 'generated_images', ['garment_id'], unique=False)
    op.create_index(op.f('ix_generated_images_id'), 'generated_images', ['id'], unique=True)
    op.create_index(op.f('ix_generated_images_mannequin_id'), 'generated_images', ['mannequin_id'], unique=False)
    op.create_index(op.f('ix_generated_images_user_id'), 'generated_images', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_generated_images_user_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_mannequin_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_id'), table_name='generated_images')
    op.drop_index(op.f('ix_generated_images_garment_id'), table_name='generated_images')
    op.drop_table('generated_images')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_mannequins_id'), table_name='mannequins')
    op.drop_table('mannequins')
    op.drop_index(op.f('ix_garments_id'), table_name='garments')
    op.drop_table('garments')
    # ### end Alembic commands ###
